/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buscapelis;

import java.io.File;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Alumno Tarde
 */
public class adivinaPeliculasVentana extends javax.swing.JFrame {

    /**
     * Creates new form adivinaPeliculasVentana
     */
    public adivinaPeliculasVentana() {
        initComponents();
        m_PartidaActual = new Partida();
        m_RetoActual = new Reto(m_PartidaActual);
        String frase = m_PartidaActual.encriptar();
        m_TxtAFrase.setText(frase);
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        m_PanMain = new javax.swing.JPanel();
        m_TxtAFrase = new javax.swing.JTextArea();
        M_PanBotones = new javax.swing.JPanel();
        m_ButA = new javax.swing.JButton();
        m_ButB = new javax.swing.JButton();
        m_ButC = new javax.swing.JButton();
        m_ButD = new javax.swing.JButton();
        m_ButE = new javax.swing.JButton();
        m_ButF = new javax.swing.JButton();
        m_ButG = new javax.swing.JButton();
        m_ButH = new javax.swing.JButton();
        m_ButI = new javax.swing.JButton();
        m_ButJ = new javax.swing.JButton();
        m_ButK = new javax.swing.JButton();
        m_ButL = new javax.swing.JButton();
        m_ButM = new javax.swing.JButton();
        m_ButN = new javax.swing.JButton();
        m_ButEnne = new javax.swing.JButton();
        m_ButO = new javax.swing.JButton();
        m_ButP = new javax.swing.JButton();
        m_ButQ = new javax.swing.JButton();
        m_ButR = new javax.swing.JButton();
        m_ButS = new javax.swing.JButton();
        m_ButT = new javax.swing.JButton();
        m_ButU = new javax.swing.JButton();
        m_ButV = new javax.swing.JButton();
        m_ButW = new javax.swing.JButton();
        m_ButX = new javax.swing.JButton();
        m_ButY = new javax.swing.JButton();
        m_ButZ = new javax.swing.JButton();
        m_But1 = new javax.swing.JButton();
        m_But2 = new javax.swing.JButton();
        m_But3 = new javax.swing.JButton();
        m_But4 = new javax.swing.JButton();
        m_But5 = new javax.swing.JButton();
        m_But6 = new javax.swing.JButton();
        m_But7 = new javax.swing.JButton();
        m_But8 = new javax.swing.JButton();
        m_But9 = new javax.swing.JButton();
        m_But0 = new javax.swing.JButton();
        m_PanAdivina = new javax.swing.JPanel();
        m_LabAdivinar = new javax.swing.JLabel();
        m_TxtFAdivinarPelicula = new javax.swing.JTextField();
        m_ButPruebaSuerte = new javax.swing.JButton();
        m_LabPuntuacion = new javax.swing.JLabel();
        m_MBarMain = new javax.swing.JMenuBar();
        m_MenPartida = new javax.swing.JMenu();
        m_MItNuevaPartida = new javax.swing.JMenuItem();
        m_MItGuardarPartida = new javax.swing.JMenuItem();
        m_MItCargarPartida = new javax.swing.JMenuItem();
        m_MenDificultad = new javax.swing.JMenu();
        m_MItFacil = new javax.swing.JMenuItem();
        m_MItIntermedio = new javax.swing.JMenuItem();
        m_MItDificil = new javax.swing.JMenuItem();
        m_MenAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Adivina Películas");

        m_PanMain.setToolTipText("");

        m_TxtAFrase.setEditable(false);
        m_TxtAFrase.setColumns(20);
        m_TxtAFrase.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        m_TxtAFrase.setRows(5);
        m_TxtAFrase.setText("Hola que pasa");

        m_ButA.setText("A");
        m_ButA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_ButAActionPerformed(evt);
            }
        });

        m_ButB.setText("B");
        m_ButB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_ButBActionPerformed(evt);
            }
        });

        m_ButC.setText("C");
        m_ButC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_ButCActionPerformed(evt);
            }
        });

        m_ButD.setText("D");
        m_ButD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_ButDActionPerformed(evt);
            }
        });

        m_ButE.setText("E");
        m_ButE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_ButEActionPerformed(evt);
            }
        });

        m_ButF.setText("F");
        m_ButF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_ButFActionPerformed(evt);
            }
        });

        m_ButG.setText("G");
        m_ButG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_ButGActionPerformed(evt);
            }
        });

        m_ButH.setText("H");
        m_ButH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_ButHActionPerformed(evt);
            }
        });

        m_ButI.setText("I");
        m_ButI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_ButIActionPerformed(evt);
            }
        });

        m_ButJ.setText("J");
        m_ButJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_ButJActionPerformed(evt);
            }
        });

        m_ButK.setText("K");
        m_ButK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_ButKActionPerformed(evt);
            }
        });

        m_ButL.setText("L");
        m_ButL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_ButLActionPerformed(evt);
            }
        });

        m_ButM.setText("M");
        m_ButM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_ButMActionPerformed(evt);
            }
        });

        m_ButN.setText("N");
        m_ButN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_ButNActionPerformed(evt);
            }
        });

        m_ButEnne.setText("Ñ");
        m_ButEnne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_ButEnneActionPerformed(evt);
            }
        });

        m_ButO.setText("O");
        m_ButO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_ButOActionPerformed(evt);
            }
        });

        m_ButP.setText("P");
        m_ButP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_ButPActionPerformed(evt);
            }
        });

        m_ButQ.setText("Q");
        m_ButQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_ButQActionPerformed(evt);
            }
        });

        m_ButR.setText("R");
        m_ButR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_ButRActionPerformed(evt);
            }
        });

        m_ButS.setText("S");
        m_ButS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_ButSActionPerformed(evt);
            }
        });

        m_ButT.setText("T");
        m_ButT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_ButTActionPerformed(evt);
            }
        });

        m_ButU.setText("U");
        m_ButU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_ButUActionPerformed(evt);
            }
        });

        m_ButV.setText("V");
        m_ButV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_ButVActionPerformed(evt);
            }
        });

        m_ButW.setText("W");
        m_ButW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_ButWActionPerformed(evt);
            }
        });

        m_ButX.setText("X");
        m_ButX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_ButXActionPerformed(evt);
            }
        });

        m_ButY.setText("Y");
        m_ButY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_ButYActionPerformed(evt);
            }
        });

        m_ButZ.setText("Z");
        m_ButZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_ButZActionPerformed(evt);
            }
        });

        m_But1.setText("1");
        m_But1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_But1ActionPerformed(evt);
            }
        });

        m_But2.setText("2");
        m_But2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_But2ActionPerformed(evt);
            }
        });

        m_But3.setText("3");
        m_But3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_But3ActionPerformed(evt);
            }
        });

        m_But4.setText("4");
        m_But4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_But4ActionPerformed(evt);
            }
        });

        m_But5.setText("5");
        m_But5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_But5ActionPerformed(evt);
            }
        });

        m_But6.setText("6");
        m_But6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_But6ActionPerformed(evt);
            }
        });

        m_But7.setText("7");
        m_But7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_But7ActionPerformed(evt);
            }
        });

        m_But8.setText("8");
        m_But8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_But8ActionPerformed(evt);
            }
        });

        m_But9.setText("9");
        m_But9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_But9ActionPerformed(evt);
            }
        });

        m_But0.setText("0");
        m_But0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_But0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout M_PanBotonesLayout = new javax.swing.GroupLayout(M_PanBotones);
        M_PanBotones.setLayout(M_PanBotonesLayout);
        M_PanBotonesLayout.setHorizontalGroup(
            M_PanBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(M_PanBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(M_PanBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(M_PanBotonesLayout.createSequentialGroup()
                        .addComponent(m_ButA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_ButB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_ButC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_ButD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_ButE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_ButF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_ButG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_ButH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_ButI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_ButJ))
                    .addGroup(M_PanBotonesLayout.createSequentialGroup()
                        .addComponent(m_ButK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_ButL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_ButM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_ButN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_ButEnne)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_ButO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_ButP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_ButQ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_ButR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_ButS))
                    .addGroup(M_PanBotonesLayout.createSequentialGroup()
                        .addComponent(m_ButT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_ButU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_ButV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_ButW)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_ButX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_ButY)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_ButZ))
                    .addGroup(M_PanBotonesLayout.createSequentialGroup()
                        .addComponent(m_But1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_But2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_But3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_But4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_But5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_But6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_But7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_But8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_But9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_But0)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        M_PanBotonesLayout.setVerticalGroup(
            M_PanBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(M_PanBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(M_PanBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_ButA)
                    .addComponent(m_ButB)
                    .addComponent(m_ButC)
                    .addComponent(m_ButD)
                    .addComponent(m_ButE)
                    .addComponent(m_ButF)
                    .addComponent(m_ButG)
                    .addComponent(m_ButH)
                    .addComponent(m_ButI)
                    .addComponent(m_ButJ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(M_PanBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_ButK)
                    .addComponent(m_ButL)
                    .addComponent(m_ButM)
                    .addComponent(m_ButN)
                    .addComponent(m_ButEnne)
                    .addComponent(m_ButO)
                    .addComponent(m_ButP)
                    .addComponent(m_ButQ)
                    .addComponent(m_ButR)
                    .addComponent(m_ButS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(M_PanBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_ButT)
                    .addComponent(m_ButU)
                    .addComponent(m_ButV)
                    .addComponent(m_ButW)
                    .addComponent(m_ButX)
                    .addComponent(m_ButY)
                    .addComponent(m_ButZ))
                .addGap(18, 18, 18)
                .addGroup(M_PanBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_But1)
                    .addComponent(m_But2)
                    .addComponent(m_But3)
                    .addComponent(m_But4)
                    .addComponent(m_But5)
                    .addComponent(m_But6)
                    .addComponent(m_But7)
                    .addComponent(m_But8)
                    .addComponent(m_But9)
                    .addComponent(m_But0))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        m_LabAdivinar.setText("Adivina la película");

        m_TxtFAdivinarPelicula.setToolTipText("Escribe tu respuesta aquí");
        m_TxtFAdivinarPelicula.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        m_TxtFAdivinarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_TxtFAdivinarPeliculaActionPerformed(evt);
            }
        });

        m_ButPruebaSuerte.setText("Prueba Suerte");
        m_ButPruebaSuerte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_ButPruebaSuerteActionPerformed(evt);
            }
        });

        m_LabPuntuacion.setText("Puntuación:");

        javax.swing.GroupLayout m_PanAdivinaLayout = new javax.swing.GroupLayout(m_PanAdivina);
        m_PanAdivina.setLayout(m_PanAdivinaLayout);
        m_PanAdivinaLayout.setHorizontalGroup(
            m_PanAdivinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(m_PanAdivinaLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(m_PanAdivinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, m_PanAdivinaLayout.createSequentialGroup()
                        .addComponent(m_LabAdivinar)
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, m_PanAdivinaLayout.createSequentialGroup()
                        .addComponent(m_ButPruebaSuerte)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, m_PanAdivinaLayout.createSequentialGroup()
                        .addGroup(m_PanAdivinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(m_LabPuntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m_TxtFAdivinarPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))))
        );
        m_PanAdivinaLayout.setVerticalGroup(
            m_PanAdivinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(m_PanAdivinaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(m_LabAdivinar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(m_TxtFAdivinarPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(m_ButPruebaSuerte)
                .addGap(18, 18, 18)
                .addComponent(m_LabPuntuacion)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout m_PanMainLayout = new javax.swing.GroupLayout(m_PanMain);
        m_PanMain.setLayout(m_PanMainLayout);
        m_PanMainLayout.setHorizontalGroup(
            m_PanMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(m_PanMainLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(M_PanBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(m_PanAdivina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, m_PanMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(m_TxtAFrase)
                .addContainerGap())
        );
        m_PanMainLayout.setVerticalGroup(
            m_PanMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(m_PanMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(m_TxtAFrase, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(m_PanMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(m_PanMainLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(M_PanBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(m_PanMainLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(m_PanAdivina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        m_MenPartida.setText("Partida");

        m_MItNuevaPartida.setText("Nueva Partida");
        m_MItNuevaPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_MItNuevaPartidaActionPerformed(evt);
            }
        });
        m_MenPartida.add(m_MItNuevaPartida);

        m_MItGuardarPartida.setText("Guardar Partida");
        m_MItGuardarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_MItGuardarPartidaActionPerformed(evt);
            }
        });
        m_MenPartida.add(m_MItGuardarPartida);

        m_MItCargarPartida.setText("Cargar Partida");
        m_MItCargarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_MItCargarPartidaActionPerformed(evt);
            }
        });
        m_MenPartida.add(m_MItCargarPartida);

        m_MBarMain.add(m_MenPartida);

        m_MenDificultad.setText("Dificultad");

        m_MItFacil.setText("Fácil");
        m_MItFacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_MItFacilActionPerformed(evt);
            }
        });
        m_MenDificultad.add(m_MItFacil);

        m_MItIntermedio.setText("Intermedio");
        m_MItIntermedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_MItIntermedioActionPerformed(evt);
            }
        });
        m_MenDificultad.add(m_MItIntermedio);

        m_MItDificil.setText("Díficil");
        m_MItDificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_MItDificilActionPerformed(evt);
            }
        });
        m_MenDificultad.add(m_MItDificil);

        m_MBarMain.add(m_MenDificultad);

        m_MenAyuda.setText("Ayuda");
        m_MBarMain.add(m_MenAyuda);

        setJMenuBar(m_MBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(m_PanMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(m_PanMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void m_ButEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_ButEActionPerformed
        m_ButE.setEnabled(false);
        m_PartidaActual.letrasMarcadas[4] = true;
        m_RetoActual.introducirLetra('E');
        m_TxtAFrase.setText(m_PartidaActual.encriptar());
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
        comprobar();
        
    }//GEN-LAST:event_m_ButEActionPerformed

    private void m_ButFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_ButFActionPerformed
        m_ButF.setEnabled(false);
        m_PartidaActual.letrasMarcadas[5] = true;
        m_RetoActual.introducirLetra('F');
        m_TxtAFrase.setText(m_PartidaActual.encriptar());
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
        comprobar();
    }//GEN-LAST:event_m_ButFActionPerformed

    private void m_ButGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_ButGActionPerformed
        m_ButG.setEnabled(false);
        m_PartidaActual.letrasMarcadas[6] = true;
        m_RetoActual.introducirLetra('G');
        m_TxtAFrase.setText(m_PartidaActual.encriptar());
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
        comprobar();
    }//GEN-LAST:event_m_ButGActionPerformed

    private void m_ButHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_ButHActionPerformed
        m_ButH.setEnabled(false);
        m_PartidaActual.letrasMarcadas[7] = true;
        m_RetoActual.introducirLetra('H');
        m_TxtAFrase.setText(m_PartidaActual.encriptar());
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
        comprobar();
    }//GEN-LAST:event_m_ButHActionPerformed

    private void m_ButIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_ButIActionPerformed
        m_ButI.setEnabled(false);
        m_PartidaActual.letrasMarcadas[8] = true;
        m_RetoActual.introducirLetra('I');
        m_TxtAFrase.setText(m_PartidaActual.encriptar());
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
        comprobar();
    }//GEN-LAST:event_m_ButIActionPerformed

    private void m_ButJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_ButJActionPerformed
        m_ButJ.setEnabled(false);
        m_PartidaActual.letrasMarcadas[9] = true;
        m_RetoActual.introducirLetra('J');
        m_TxtAFrase.setText(m_PartidaActual.encriptar());
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
        comprobar();
    }//GEN-LAST:event_m_ButJActionPerformed

    private void m_ButKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_ButKActionPerformed
        m_ButK.setEnabled(false);
        m_PartidaActual.letrasMarcadas[10] = true;
        m_RetoActual.introducirLetra('K');
        m_TxtAFrase.setText(m_PartidaActual.encriptar());
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
        comprobar();
    }//GEN-LAST:event_m_ButKActionPerformed

    private void m_ButLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_ButLActionPerformed
        m_ButL.setEnabled(false);
        m_PartidaActual.letrasMarcadas[11] = true;
        m_RetoActual.introducirLetra('L');
        m_TxtAFrase.setText(m_PartidaActual.encriptar());
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
        comprobar();
    }//GEN-LAST:event_m_ButLActionPerformed

    private void m_ButMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_ButMActionPerformed
        m_ButM.setEnabled(false);
        m_PartidaActual.letrasMarcadas[12] = true;
        m_RetoActual.introducirLetra('M');
        m_TxtAFrase.setText(m_PartidaActual.encriptar());
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
        comprobar();
    }//GEN-LAST:event_m_ButMActionPerformed

    private void m_ButNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_ButNActionPerformed
        m_ButN.setEnabled(false);
        m_PartidaActual.letrasMarcadas[13] = true;
        m_RetoActual.introducirLetra('N');
        m_TxtAFrase.setText(m_PartidaActual.encriptar());
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
        comprobar();
    }//GEN-LAST:event_m_ButNActionPerformed

    private void m_ButEnneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_ButEnneActionPerformed
        m_ButEnne.setEnabled(false);
        m_PartidaActual.letrasMarcadas[14] = true;
        m_RetoActual.introducirLetra('Ñ');
        m_TxtAFrase.setText(m_PartidaActual.encriptar());
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
        comprobar();
    }//GEN-LAST:event_m_ButEnneActionPerformed

    private void m_ButOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_ButOActionPerformed
        m_ButO.setEnabled(false);
        m_PartidaActual.letrasMarcadas[15] = true;
        m_RetoActual.introducirLetra('O');
        m_TxtAFrase.setText(m_PartidaActual.encriptar());
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
        comprobar();
    }//GEN-LAST:event_m_ButOActionPerformed

    private void m_ButPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_ButPActionPerformed
        m_ButP.setEnabled(false);
        m_PartidaActual.letrasMarcadas[16] = true;
        m_RetoActual.introducirLetra('P');
        m_TxtAFrase.setText(m_PartidaActual.encriptar());
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
        comprobar();
    }//GEN-LAST:event_m_ButPActionPerformed

    private void m_ButQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_ButQActionPerformed
        m_ButQ.setEnabled(false);
        m_PartidaActual.letrasMarcadas[17] = true;
        m_RetoActual.introducirLetra('Q');
        m_TxtAFrase.setText(m_PartidaActual.encriptar());
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
        comprobar();
    }//GEN-LAST:event_m_ButQActionPerformed

    private void m_ButRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_ButRActionPerformed
        m_ButR.setEnabled(false);
        m_PartidaActual.letrasMarcadas[18] = true;
        m_RetoActual.introducirLetra('R');
        m_TxtAFrase.setText(m_PartidaActual.encriptar());
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
        comprobar();
    }//GEN-LAST:event_m_ButRActionPerformed

    private void m_ButSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_ButSActionPerformed
        m_ButS.setEnabled(false);
        m_PartidaActual.letrasMarcadas[19] = true;
        m_RetoActual.introducirLetra('S');
        m_TxtAFrase.setText(m_PartidaActual.encriptar());
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
        comprobar();
    }//GEN-LAST:event_m_ButSActionPerformed

    private void m_ButTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_ButTActionPerformed
        m_ButT.setEnabled(false);
        m_PartidaActual.letrasMarcadas[20] = true;
        m_RetoActual.introducirLetra('T');
        m_TxtAFrase.setText(m_PartidaActual.encriptar());
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
        comprobar();
    }//GEN-LAST:event_m_ButTActionPerformed

    private void m_ButUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_ButUActionPerformed
        m_ButU.setEnabled(false);
        m_PartidaActual.letrasMarcadas[21] = true;
        m_RetoActual.introducirLetra('U');
        m_TxtAFrase.setText(m_PartidaActual.encriptar());
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
        comprobar();
    }//GEN-LAST:event_m_ButUActionPerformed

    private void m_ButVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_ButVActionPerformed
        m_ButV.setEnabled(false);
        m_PartidaActual.letrasMarcadas[22] = true;
        m_RetoActual.introducirLetra('V');
        m_TxtAFrase.setText(m_PartidaActual.encriptar());
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
        comprobar();
    }//GEN-LAST:event_m_ButVActionPerformed

    private void m_ButWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_ButWActionPerformed
        m_ButW.setEnabled(false);
        m_PartidaActual.letrasMarcadas[23] = true;
        m_RetoActual.introducirLetra('W');
        m_TxtAFrase.setText(m_PartidaActual.encriptar());
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
        comprobar();
    }//GEN-LAST:event_m_ButWActionPerformed

    private void m_ButXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_ButXActionPerformed
        m_ButX.setEnabled(false);
        m_PartidaActual.letrasMarcadas[24] = true;
        m_RetoActual.introducirLetra('X');
        m_TxtAFrase.setText(m_PartidaActual.encriptar());
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
        comprobar();
    }//GEN-LAST:event_m_ButXActionPerformed

    private void m_ButZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_ButZActionPerformed
        m_ButZ.setEnabled(false);
        m_PartidaActual.letrasMarcadas[26] = true;
        m_RetoActual.introducirLetra('Z');
        m_TxtAFrase.setText(m_PartidaActual.encriptar());
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
    }//GEN-LAST:event_m_ButZActionPerformed

    private void m_ButYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_ButYActionPerformed
        m_ButY.setEnabled(false);
        m_PartidaActual.letrasMarcadas[25] = true;
        m_RetoActual.introducirLetra('Y');
        m_TxtAFrase.setText(m_PartidaActual.encriptar());
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
        comprobar();
    }//GEN-LAST:event_m_ButYActionPerformed

    private void m_But1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_But1ActionPerformed
        m_But1.setEnabled(false);
        m_PartidaActual.letrasMarcadas[28] = true;
        m_RetoActual.introducirLetra('1');
        m_TxtAFrase.setText(m_PartidaActual.encriptar());
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
        comprobar();
    }//GEN-LAST:event_m_But1ActionPerformed

    private void m_But0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_But0ActionPerformed
        m_But0.setEnabled(false);
        m_PartidaActual.letrasMarcadas[27] = true;
        m_RetoActual.introducirLetra('0');
        m_TxtAFrase.setText(m_PartidaActual.encriptar());
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
        comprobar();
    }//GEN-LAST:event_m_But0ActionPerformed

    private void m_But2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_But2ActionPerformed
        m_But2.setEnabled(false);
        m_PartidaActual.letrasMarcadas[29] = true;
        m_RetoActual.introducirLetra('2');
        m_TxtAFrase.setText(m_PartidaActual.encriptar());
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
        comprobar();
    }//GEN-LAST:event_m_But2ActionPerformed

    private void m_But3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_But3ActionPerformed
        m_But3.setEnabled(false);
        m_PartidaActual.letrasMarcadas[30] = true;
        m_RetoActual.introducirLetra('3');
        m_TxtAFrase.setText(m_PartidaActual.encriptar());
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
        comprobar();
    }//GEN-LAST:event_m_But3ActionPerformed

    private void m_But4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_But4ActionPerformed
        m_But4.setEnabled(false);
        m_PartidaActual.letrasMarcadas[31] = true;
        m_RetoActual.introducirLetra('4');
        m_TxtAFrase.setText(m_PartidaActual.encriptar());
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
        comprobar();
    }//GEN-LAST:event_m_But4ActionPerformed

    private void m_But6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_But6ActionPerformed
        m_But6.setEnabled(false);
        m_PartidaActual.letrasMarcadas[33] = true;
        m_RetoActual.introducirLetra('6');
        m_TxtAFrase.setText(m_PartidaActual.encriptar());
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
        comprobar();
    }//GEN-LAST:event_m_But6ActionPerformed

    private void m_But5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_But5ActionPerformed
        m_But5.setEnabled(false);
        m_PartidaActual.letrasMarcadas[32] = true;
        m_RetoActual.introducirLetra('5');
        m_TxtAFrase.setText(m_PartidaActual.encriptar());
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
        comprobar();
    }//GEN-LAST:event_m_But5ActionPerformed

    private void m_But7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_But7ActionPerformed
        m_But7.setEnabled(false);
        m_PartidaActual.letrasMarcadas[34] = true;
        m_RetoActual.introducirLetra('7');
        m_TxtAFrase.setText(m_PartidaActual.encriptar());
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
        comprobar();
    }//GEN-LAST:event_m_But7ActionPerformed

    private void m_But8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_But8ActionPerformed
        m_But8.setEnabled(false);
        m_PartidaActual.letrasMarcadas[35] = true;
        m_RetoActual.introducirLetra('8');
        m_TxtAFrase.setText(m_PartidaActual.encriptar());
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
        comprobar();
    }//GEN-LAST:event_m_But8ActionPerformed

    private void m_But9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_But9ActionPerformed
        m_But9.setEnabled(false);
        m_PartidaActual.letrasMarcadas[36] = true;
        m_RetoActual.introducirLetra('9');
        m_TxtAFrase.setText(m_PartidaActual.encriptar());
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
        comprobar();
    }//GEN-LAST:event_m_But9ActionPerformed

    private void m_TxtFAdivinarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_TxtFAdivinarPeliculaActionPerformed
       //No se hace nada, eso lo hace el botón Prueba suerte
    }//GEN-LAST:event_m_TxtFAdivinarPeliculaActionPerformed

    
    
    private void m_ButPruebaSuerteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_ButPruebaSuerteActionPerformed
        // Se llama al metodo de partida para comprobar la frase, si acierta, gana la partida
        // Si no pierde X puntos y continua.
        
        String respuesta = sinTildes(m_TxtFAdivinarPelicula.getText());
        boolean victoria = m_RetoActual.comprobarTitulo(respuesta);
        
        if (! victoria){
            m_LabPuntuacion.setText("Puntuación: " + m_RetoActual.getPuntos());
        }
        else{
            m_LabPuntuacion.setText("¡Enhorabuena! Has conseguido " + m_RetoActual.getPuntos()+" puntos");
            m_TxtAFrase.setText(m_RetoActual.getTituloOriginal());
        }
        m_TxtFAdivinarPelicula.setText(null);
    }//GEN-LAST:event_m_ButPruebaSuerteActionPerformed

    private void m_ButDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_ButDActionPerformed
        m_ButD.setEnabled(false);
        m_PartidaActual.letrasMarcadas[3] = true;
        m_RetoActual.introducirLetra('D');
        m_TxtAFrase.setText(m_PartidaActual.encriptar());
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
        comprobar();
    }//GEN-LAST:event_m_ButDActionPerformed

    private void m_ButAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_ButAActionPerformed
        m_ButA.setEnabled(false);
        m_PartidaActual.letrasMarcadas[0] = true;
        m_RetoActual.introducirLetra('A');
        m_TxtAFrase.setText(m_PartidaActual.encriptar());
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
        comprobar();
    }//GEN-LAST:event_m_ButAActionPerformed

    private void m_MItGuardarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_MItGuardarPartidaActionPerformed
        JFileChooser fc = new JFileChooser();
        int returnVal = fc.showSaveDialog(/*ClaseDelFormularioPadre.*/this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            try {
                var ous = new ObjectOutputStream(Files.newOutputStream(Path.of(fc.getSelectedFile().getAbsolutePath())));
                ous.writeObject(m_PartidaActual);
            } catch (IOException ex) {
                Logger.getLogger(adivinaPeliculasVentana.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println("Abriendo fichero: " + fc.getSelectedFile().getName() + ".");
        } else {
        System.out.println("El usuario no le dio al botón aceptar.");
        }
    }//GEN-LAST:event_m_MItGuardarPartidaActionPerformed

    private void m_MItNuevaPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_MItNuevaPartidaActionPerformed
        nuevaPartida();
    }//GEN-LAST:event_m_MItNuevaPartidaActionPerformed

    private void m_MItCargarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_MItCargarPartidaActionPerformed
        JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(/*ClaseDelFormularioPadre.*/this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            
             //Aquí podemos trabajar con el File como de costumbre
            System.out.println("Abriendo fichero: " + fc.getSelectedFile().getName() + ".");
        } else {
        System.out.println("El usuario no le dio al botón aceptar.");
        }
    }//GEN-LAST:event_m_MItCargarPartidaActionPerformed

    private void m_ButBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_ButBActionPerformed
        m_ButB.setEnabled(false);
        m_PartidaActual.letrasMarcadas[1] = true;
        m_RetoActual.introducirLetra('B');
        m_TxtAFrase.setText(m_PartidaActual.encriptar());
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
        comprobar();
    }//GEN-LAST:event_m_ButBActionPerformed

    private void m_ButCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_ButCActionPerformed
        m_ButC.setEnabled(false);
        m_PartidaActual.letrasMarcadas[2] = true;
        m_RetoActual.introducirLetra('C');
        m_TxtAFrase.setText(m_PartidaActual.encriptar());
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
        comprobar();
    }//GEN-LAST:event_m_ButCActionPerformed

    private void m_MItFacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_MItFacilActionPerformed
        m_DificultadActual = 1;
        m_PartidaActual.setDificultad(m_DificultadActual);
        nuevaPartida();
    }//GEN-LAST:event_m_MItFacilActionPerformed

    private void m_MItIntermedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_MItIntermedioActionPerformed
        m_DificultadActual = 3;
        m_PartidaActual.setDificultad(m_DificultadActual);
        nuevaPartida();
    }//GEN-LAST:event_m_MItIntermedioActionPerformed

    private void m_MItDificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_MItDificilActionPerformed
        m_DificultadActual = 5;
        m_PartidaActual.setDificultad(m_DificultadActual);
        nuevaPartida();
    }//GEN-LAST:event_m_MItDificilActionPerformed
    
    private void comprobar(){
        boolean r = true;
        for (int k = 0; k < m_RetoActual.getAciertos().length; k++){
            if (m_RetoActual.getAciertos()[k] == false){
                r = false;
                break;
            }
        }
        
        if (r == true){
            m_LabPuntuacion.setText("¡Enhorabuena! Has conseguido " + m_RetoActual.getPuntos());
        }
        
        if (m_RetoActual.getPuntos() <= 0){
            m_LabPuntuacion.setText("Oh, has perdido");
            m_TxtAFrase.setText(m_RetoActual.getTituloOriginal());
        }
    }
    
    private void nuevaPartida(){
        m_PartidaActual = new Partida();
        m_RetoActual = new Reto(m_PartidaActual);
        m_PartidaActual.setDificultad(m_DificultadActual);
        String frase = m_PartidaActual.encriptar();
        m_TxtAFrase.setText(frase);
        m_LabPuntuacion.setText("Puntuación: "+m_RetoActual.getPuntos());
        reiniciarBotones();
    }
    
    protected void reiniciarBotones(){
        m_ButA.setEnabled(true);
        m_ButB.setEnabled(true);
        m_ButC.setEnabled(true);
        m_ButD.setEnabled(true);
        m_ButE.setEnabled(true);
        m_ButF.setEnabled(true);
        m_ButG.setEnabled(true);
        m_ButH.setEnabled(true);
        m_ButI.setEnabled(true);
        m_ButJ.setEnabled(true);
        m_ButK.setEnabled(true);
        m_ButL.setEnabled(true);
        m_ButM.setEnabled(true);
        m_ButN.setEnabled(true);
        m_ButEnne.setEnabled(true);
        m_ButO.setEnabled(true);
        m_ButP.setEnabled(true);
        m_ButQ.setEnabled(true);
        m_ButR.setEnabled(true);
        m_ButS.setEnabled(true);
        m_ButT.setEnabled(true);
        m_ButU.setEnabled(true);
        m_ButV.setEnabled(true);
        m_ButW.setEnabled(true);
        m_ButX.setEnabled(true);
        m_ButY.setEnabled(true);
        m_ButZ.setEnabled(true);
        m_But0.setEnabled(true);
        m_But1.setEnabled(true);
        m_But2.setEnabled(true);
        m_But3.setEnabled(true);
        m_But4.setEnabled(true);
        m_But5.setEnabled(true);
        m_But6.setEnabled(true);
        m_But7.setEnabled(true);
        m_But8.setEnabled(true);
        m_But9.setEnabled(true);
    }
    
    protected String sinTildes(String tituloOriginal){
        String to = tituloOriginal.toUpperCase();
        String tituloSinTildes = "";
        for (int k = 0; k< to.length(); k++){
            
            if (tituloOriginal.charAt(k) == 'a' || tituloOriginal.charAt(k) == 'á' || tituloOriginal.charAt(k) == 'Á'){
                tituloSinTildes += "A";
            }
            else if (tituloOriginal.charAt(k) == 'e' || tituloOriginal.charAt(k) == 'é' || tituloOriginal.charAt(k) == 'É'){
                tituloSinTildes += "E";
            }
            else if (tituloOriginal.charAt(k) == 'i' || tituloOriginal.charAt(k) == 'í' || tituloOriginal.charAt(k) == 'Í'){
                tituloSinTildes += "I";
            }
            else if (tituloOriginal.charAt(k) == 'o' || tituloOriginal.charAt(k) == 'ó' || tituloOriginal.charAt(k) == 'Ó'){
                tituloSinTildes += "O";
            }
            else if (tituloOriginal.charAt(k) == 'u' || tituloOriginal.charAt(k) == 'ú' || tituloOriginal.charAt(k) == 'Ú'){
                tituloSinTildes += "U";
            }
            else{
                tituloSinTildes += to.charAt(k);
            }
        }
        
        return tituloSinTildes;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adivinaPeliculasVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adivinaPeliculasVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adivinaPeliculasVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adivinaPeliculasVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adivinaPeliculasVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel M_PanBotones;
    private javax.swing.JButton m_But0;
    private javax.swing.JButton m_But1;
    private javax.swing.JButton m_But2;
    private javax.swing.JButton m_But3;
    private javax.swing.JButton m_But4;
    private javax.swing.JButton m_But5;
    private javax.swing.JButton m_But6;
    private javax.swing.JButton m_But7;
    private javax.swing.JButton m_But8;
    private javax.swing.JButton m_But9;
    private javax.swing.JButton m_ButA;
    private javax.swing.JButton m_ButB;
    private javax.swing.JButton m_ButC;
    private javax.swing.JButton m_ButD;
    private javax.swing.JButton m_ButE;
    private javax.swing.JButton m_ButEnne;
    private javax.swing.JButton m_ButF;
    private javax.swing.JButton m_ButG;
    private javax.swing.JButton m_ButH;
    private javax.swing.JButton m_ButI;
    private javax.swing.JButton m_ButJ;
    private javax.swing.JButton m_ButK;
    private javax.swing.JButton m_ButL;
    private javax.swing.JButton m_ButM;
    private javax.swing.JButton m_ButN;
    private javax.swing.JButton m_ButO;
    private javax.swing.JButton m_ButP;
    private javax.swing.JButton m_ButPruebaSuerte;
    private javax.swing.JButton m_ButQ;
    private javax.swing.JButton m_ButR;
    private javax.swing.JButton m_ButS;
    private javax.swing.JButton m_ButT;
    private javax.swing.JButton m_ButU;
    private javax.swing.JButton m_ButV;
    private javax.swing.JButton m_ButW;
    private javax.swing.JButton m_ButX;
    private javax.swing.JButton m_ButY;
    private javax.swing.JButton m_ButZ;
    private javax.swing.JLabel m_LabAdivinar;
    private javax.swing.JLabel m_LabPuntuacion;
    private javax.swing.JMenuBar m_MBarMain;
    private javax.swing.JMenuItem m_MItCargarPartida;
    private javax.swing.JMenuItem m_MItDificil;
    private javax.swing.JMenuItem m_MItFacil;
    private javax.swing.JMenuItem m_MItGuardarPartida;
    private javax.swing.JMenuItem m_MItIntermedio;
    private javax.swing.JMenuItem m_MItNuevaPartida;
    private javax.swing.JMenu m_MenAyuda;
    private javax.swing.JMenu m_MenDificultad;
    private javax.swing.JMenu m_MenPartida;
    private javax.swing.JPanel m_PanAdivina;
    private javax.swing.JPanel m_PanMain;
    private javax.swing.JTextArea m_TxtAFrase;
    private javax.swing.JTextField m_TxtFAdivinarPelicula;
    // End of variables declaration//GEN-END:variables
    private Partida m_PartidaActual;
    private Reto m_RetoActual;
    private int m_DificultadActual;
    /*
    private static final char [] ARRAY_ABECEDARIO = {
        'A', 'B', 'C', 'D', 'E', 'F',
        'G', 'H', 'I', 'J', 'K', 'L',
        'M', 'N', 'Ñ', 'O', 'P', 'K',
        'R', 'S', 'T', 'U', 'V', 'W',
        'X', 'Y', 'Z'
    };
    private static final char [] ARRAY_NUMEROS = {
        '0', '1', '2', '3', '4',
        '5', '6', '7', '8', '9'
    };
    
*/
}
